"""한글 태그를 영문으로 통합 정규화

처리 방식:
  1. YAML frontmatter tags: [...] 업데이트
  2. 본문 ## 서지정보 태그 해시태그 업데이트
  3. 중복 제거 (한글+영문 동시 존재 시 영문 유지)
"""

import os
import re
from pathlib import Path

from config import MARKDOWN_DIR

# ── 한글 → 영문 태그 매핑 ────────────────────────────────────────────────────

TAG_MAP = {
    # 지식 공유
    "지식공유": "knowledge-sharing",
    "지식-공유": "knowledge-sharing",
    "지식공유행동": "knowledge-sharing",
    "지식-공유-행동": "knowledge-sharing",
    "지식공유-의도": "knowledge-sharing-intention",
    "지식공유정도": "knowledge-sharing",
    "지식-공유(ks)": "knowledge-sharing",
    "지식-공유방식": "knowledge-sharing",
    "형식적-지식-공유": "explicit-knowledge-sharing",
    "암묵적-지식-공유": "tacit-knowledge-sharing",

    # 지식 경영
    "지식경영": "knowledge-management",
    "지식-경영": "knowledge-management",
    "지식-관리": "knowledge-management",
    "지식관리": "knowledge-management",
    "지식-관리(km)": "knowledge-management",
    "지식-관리(knowledge-management)": "knowledge-management",
    "지식경영성과": "knowledge-management-performance",
    "지식경영시스템": "knowledge-management-system",
    "지식관리시스템": "knowledge-management-system",
    "지식-관리-시스템(kms)": "knowledge-management-system",
    "지식-관리-지향성": "knowledge-management-orientation",

    # 지식 창출
    "지식창출": "knowledge-creation",
    "지식-창조": "knowledge-creation",
    "지식-창출": "knowledge-creation",
    "지식-창출-이론": "knowledge-creation",
    "기업가적-지식-창출": "entrepreneurial-knowledge-creation",
    "내부-기술지식창출": "internal-knowledge-creation",
    "외부-기술지식습득": "external-knowledge-acquisition",

    # 지식 유형
    "암묵지": "tacit-knowledge",
    "암묵적-지식": "tacit-knowledge",
    "명시적-지식": "explicit-knowledge",
    "형식지": "explicit-knowledge",
    "기업가적-암묵지": "entrepreneurial-tacit-knowledge",
    "지식기반관점(kbv)": "knowledge-based-view",
    "지식-기반-관점": "knowledge-based-view",
    "지식기반비즈니스(kibs)": "knowledge-intensive-services",
    "지식서비스산업": "knowledge-intensive-services",
    "지식": "knowledge",
    "지식-근로자": "knowledge-worker",
    "지식-스필오버": "knowledge-spillover",
    "지식-외부효과": "knowledge-spillover",
    "지식전이": "knowledge-transfer",
    "지식-전송": "knowledge-transfer",
    "지식통합": "knowledge-integration",
    "지식-흐름": "knowledge-flow",
    "지식-구성": "knowledge-construction",
    "지식활동": "knowledge-activities",
    "지식재사용": "knowledge-reuse",
    "지식-재결합": "knowledge-recombination",
    "지식-영역성": "knowledge-territoriality",
    "지식-경제": "knowledge-economy",
    "지식인프라": "knowledge-infrastructure",
    "지식프로세스": "knowledge-process",
    "지식통합": "knowledge-integration",
    "지식기반관점(kbv)": "knowledge-based-view",
    "연결-지식": "connected-knowledge",
    "실질적-지식": "substantive-knowledge",

    # 기업가정신
    "기업가정신": "entrepreneurship",
    "기업가-정신": "entrepreneurship",
    "기업가적-지향성": "entrepreneurial-orientation",
    "기업가적-지향성(eo)": "entrepreneurial-orientation",
    "기업가-정신-지향성": "entrepreneurial-orientation",
    "창업지향성": "entrepreneurial-orientation",
    "기업가적-관리": "entrepreneurial-management",
    "기업가적-기회": "entrepreneurial-opportunity",
    "기업가적-열정": "entrepreneurial-passion",
    "기업가적-동기": "entrepreneurial-motivation",
    "기업가적-혁신성": "entrepreneurial-innovativeness",
    "기업가역량": "entrepreneurial-capability",
    "기업가": "entrepreneur",
    "기업가-정신-동기": "entrepreneurial-motivation",
    "사내기업가정신": "intrapreneurship",
    "국제기업가정신": "international-entrepreneurship",
    "디지털-기업가정신": "digital-entrepreneurship",
    "디지털-창업": "digital-entrepreneurship",
    "스마트-기업가정신": "smart-entrepreneurship",
    "지속가능한-기업가정신": "sustainable-entrepreneurship",
    "ai-창업": "ai-entrepreneurship",
    "여성-기업가": "female-entrepreneur",
    "인공지능-기업가-정신": "ai-entrepreneurship",
    "전략적-기업가-정신": "strategic-entrepreneurship",
    "기업가적-지식-창출": "entrepreneurial-knowledge-creation",
    "창업가경험(entrepreneurial-experience)": "entrepreneurial-experience",
    "개인적-기업가-지향성(ieo)": "individual-entrepreneurial-orientation",

    # 창업
    "창업": "startup",
    "벤처창업": "venture",
    "벤처-창업": "venture",
    "스타트업": "startup",
    "창업기업": "startup",
    "창업기업성과": "startup-performance",
    "스타트업-성공-예측": "startup-success-prediction",
    "스타트업-성과": "startup-performance",
    "스타트업금융": "startup-finance",
    "창업-팀": "startup-team",
    "창업-교육": "entrepreneurship-education",
    "창업교육": "entrepreneurship-education",
    "기업가정신-교육": "entrepreneurship-education",
    "창업-의도": "entrepreneurial-intention",
    "창업-생태계": "entrepreneurial-ecosystem",
    "혁신-생태계": "innovation-ecosystem",
    "벤처생태계": "venture-ecosystem",
    "벤처-캐피털": "venture-capital",
    "벤처창업": "venture",
    "인큐베이션센터": "incubation-center",
    "창업연구": "entrepreneurship-research",
    "창업가": "entrepreneur",
    "초기-창업": "early-stage-startup",
    "초기-단계-기업": "early-stage-startup",
    "창업-생태계": "entrepreneurial-ecosystem",
    "신생-기업의-취약성(liability-of-newness)": "liability-of-newness",

    # 혁신
    "혁신": "innovation",
    "혁신행동": "innovative-behavior",
    "혁신행위": "innovative-behavior",
    "혁신-행동": "innovative-behavior",
    "혁신적-업무-행동": "innovative-work-behavior",
    "혁신적-행동": "innovative-behavior",
    "혁신성과": "innovation-performance",
    "혁신-성과": "innovation-performance",
    "혁신역량": "innovation-capability",
    "혁신-역량": "innovation-capability",
    "기술혁신역량": "technological-innovation-capability",
    "혁신성": "innovativeness",
    "혁신관리": "innovation-management",
    "경영혁신": "management-innovation",
    "혁신성장": "innovation-driven-growth",
    "기술혁신": "technological-innovation",
    "기술-혁신": "technological-innovation",
    "개방형-혁신": "open-innovation",
    "개방형혁신": "open-innovation",
    "파괴적-혁신": "disruptive-innovation",
    "비즈니스-모델-혁신": "business-model-innovation",
    "비즈니스-모델-혁신(bmi)": "business-model-innovation",
    "점진적-혁신": "incremental-innovation",
    "급진적-혁신": "radical-innovation",
    "혁신-프로세스": "innovation-process",
    "혁신-전략": "innovation-strategy",
    "혁신-문화": "innovation-culture",
    "혁신-실패": "innovation-failure",
    "지속-가능한-혁신": "sustainable-innovation",
    "혁신활동": "innovation-activities",
    "기업혁신활동": "corporate-innovation-activities",
    "양면적혁신활동": "ambidextrous-innovation",
    "공정-혁신": "process-innovation",
    "제품-혁신": "product-innovation",
    "제품혁신": "product-innovation",
    "녹색-혁신": "green-innovation",
    "혁신-성향": "innovation-propensity",
    "교육-혁신": "educational-innovation",
    "혁신-생태계": "innovation-ecosystem",

    # 조직
    "조직-문화": "organizational-culture",
    "조직문화": "organizational-culture",
    "조직-성과": "organizational-performance",
    "조직성과": "organizational-performance",
    "조직-성과(organizational-performance)": "organizational-performance",
    "조직-혁신": "organizational-innovation",
    "조직-혁신성": "organizational-innovativeness",
    "조직-구조": "organizational-structure",
    "조직구조": "organizational-structure",
    "조직-학습": "organizational-learning",
    "조직학습": "organizational-learning",
    "학습조직": "learning-organization",
    "조직-행동": "organizational-behavior",
    "조직행동론": "organizational-behavior",
    "조직-역량": "organizational-capability",
    "조직역량": "organizational-capability",
    "조직-이론": "organizational-theory",
    "조직이론": "organizational-theory",
    "조직유형론": "organizational-typology",
    "조직-진화": "organizational-evolution",
    "조직-커뮤니케이션": "organizational-communication",
    "조직-신뢰": "organizational-trust",
    "조직신뢰": "organizational-trust",
    "조직-몰입": "organizational-commitment",
    "조직몰입": "organizational-commitment",
    "조직-동일시": "organizational-identification",
    "조직-회복력": "organizational-resilience",
    "조직-민첩성": "organizational-agility",
    "조직민첩성": "organizational-agility",
    "조직기억": "organizational-memory",
    "조직-정보-처리-이론": "organizational-information-processing-theory",
    "조직-정보-처리-이론(oipt)": "organizational-information-processing-theory",
    "조직 ": "organization",
    "조직": "organization",
    "조직-녹색-문화": "green-organizational-culture",
    "조직-간-협력": "inter-organizational-cooperation",

    # 성과
    "경영성과": "firm-performance",
    "기업성과": "firm-performance",
    "기업-성과": "firm-performance",
    "성과": "performance",
    "재무성과": "financial-performance",
    "비재무적성과": "non-financial-performance",
    "팀-성과": "team-performance",
    "팀성과": "team-performance",
    "직무-성과": "job-performance",
    "사업-성과": "business-performance",
    "비즈니스-성과": "business-performance",
    "개인성과": "individual-performance",
    "수출-성과": "export-performance",
    "수출성과": "export-performance",
    "창업기업성과": "startup-performance",
    "스타트업-성과": "startup-performance",
    "경쟁가치모형": "competing-values-framework",
    "경영자능력": "managerial-capability",
    "미래성과": "future-performance",
    "지식경영성과": "knowledge-management-performance",

    # 리더십 및 HRM
    "리더십": "leadership",
    "변혁적-리더십": "transformational-leadership",
    "거래적-리더십": "transactional-leadership",
    "윤리적-리더십": "ethical-leadership",
    "진성-리더십": "authentic-leadership",
    "임파워링-리더십": "empowering-leadership",
    "역설적-리더-행동": "paradoxical-leader-behavior",
    "리더-마음챙김": "leader-mindfulness",
    "리더-구성원-교환관계": "lmx",
    "lmx-차별화(lmxd)": "lmx-differentiation",
    "인적자원개발": "human-resource-development",
    "인적-자원-관리": "human-resource-management",
    "인적-자원-관리(hrm)": "human-resource-management",
    "인사프랙티스": "hr-practices",
    "인사-관리": "personnel-management",
    "고성과-인적-자원-관행": "high-performance-work-practices",
    "중간-관리자": "middle-management",
    "인적자본": "human-capital",
    "인적-자본": "human-capital",
    "인적자원혁신성": "hr-innovativeness",
    "인적-네트워크": "personal-network",
    "최고경영진-지원": "top-management-support",
    "최고경영자": "ceo",
    "차상위-리더": "second-level-leader",

    # 중소기업
    "중소기업": "smes",
    "중소기업(smes)": "smes",
    "남아프리카-공화국-중소기업": "smes",
    "중소제조기업": "manufacturing-smes",
    "소기업(sme)": "smes",
    "수출중소기업": "exporting-smes",
    "기술창업기업": "technology-startup",
    "대기업": "large-enterprise",

    # 연구방법
    "구조방정식": "structural-equation-modeling",
    "구조방정식모형": "structural-equation-modeling",
    "구조방정식모델": "structural-equation-modeling",
    "구조방정식-모델링": "structural-equation-modeling",
    "구조방정식-모델링(sem)": "structural-equation-modeling",
    "구조방정식-(sem-pls)": "pls-sem",
    "매개효과": "mediating-effect",
    "매개-효과": "mediating-effect",
    "매개-효과-분석": "mediating-effect",
    "조절효과": "moderating-effect",
    "조절된-매개": "moderated-mediation",
    "메타-분석": "meta-analysis",
    "체계적문헌고찰": "systematic-literature-review",
    "체계적-문헌-고찰": "systematic-literature-review",
    "체계적-문헌-검토": "systematic-literature-review",
    "질적-연구": "qualitative-research",
    "사례-연구": "case-study",
    "종단적-연구": "longitudinal-study",
    "종단연구": "longitudinal-study",
    "pls분석": "pls",
    "계량서지학": "bibliometrics",
    "키워드분석": "keyword-analysis",
    "텍스트-분석": "text-analysis",
    "텍스트-네트워크-분석": "text-network-analysis",
    "네트워크분석": "network-analysis",
    "사회연결망분석(sna)": "social-network-analysis",
    "소셜-네트워크-분석(sna)": "social-network-analysis",
    "소셜-미디어-분석": "social-media-analysis",
    "콘텐츠-분석": "content-analysis",
    "패널분석": "panel-analysis",
    "패널회귀분석": "panel-regression",
    "설문도구": "survey-instrument",
    "척도개발": "scale-development",
    "척도-개발": "scale-development",
    "척도-개발-및-타당화": "scale-development",
    "확인-요인-분석": "confirmatory-factor-analysis",
    "실증-분석": "empirical-analysis",
    "연구방법론": "research-methodology",
    "연구동향": "research-trends",
    "연구변수": "research-variables",
    "개념적-프레임워크": "conceptual-framework",
    "개념-모델": "conceptual-model",
    "이론적-리뷰": "theoretical-review",
    "문헌고찰": "literature-review",
    "문헌-검토": "literature-review",
    "메타-분석": "meta-analysis",
    "경험적-설문-조사": "empirical-survey",

    # 인공지능/기술
    "인공지능": "artificial-intelligence",
    "인공지능(ai)": "artificial-intelligence",
    "머신러닝": "machine-learning",
    "기계학습": "machine-learning",
    "딥러닝": "deep-learning",
    "강화학습": "reinforcement-learning",
    "생성형-ai": "generative-ai",
    "생성형-인공지능": "generative-ai",
    "신경망-ai": "neural-network",
    "인공신경망(ann)": "neural-network",
    "트랜스포머": "transformer",
    "대규모-언어-모델(llm)": "large-language-model",
    "거대언어모델(llm)": "large-language-model",
    "ict-기술": "ict",
    "핀테크": "fintech",
    "핀테크-혁신": "fintech-innovation",
    "빅데이터": "big-data",
    "빅데이터-분석": "big-data-analytics",
    "빅데이터-거버넌스": "big-data-governance",
    "빅데이터-관리-역량": "big-data-management-capability",
    "데이터-중심-문화": "data-driven-culture",
    "데이터-마이닝": "data-mining",
    "데이터-마이닝(data-mining)": "data-mining",
    "데이터-과학": "data-science",
    "온톨로지": "ontology",
    "온톨로지-엔지니어링": "ontology-engineering",
    "디지털-전환": "digital-transformation",
    "디지털전환": "digital-transformation",
    "4차-산업혁명": "industry-4.0",
    "4차산업혁명": "industry-4.0",
    "ai-도입": "ai-adoption",
    "ai-거버넌스": "ai-governance",
    "ai-윤리": "ai-ethics",
    "ai-의사결정": "ai-decision-making",
    "ai-투명성": "ai-transparency",
    "ai-pen-프레임워크": "ai-pen-framework",
    "인공지능-전략": "ai-strategy",
    "인간-ai-협업": "human-ai-collaboration",
    "설명가능한-인공지능": "explainable-ai",
    "인공지능-윤리": "ai-ethics",
    "멀티모달": "multimodal",
    "기호적-ai": "symbolic-ai",
    "신경과학적영감": "neuroscientific-inspiration",
    "범용인공지능(agi)": "agi",
    "뇌과학": "neuroscience",
    "스마트팩토리": "smart-factory",
    "사이버물리시스템(cps)": "cyber-physical-system",
    "정보기술": "information-technology",
    "정보-시스템": "information-systems",
    "정보-처리-프레임워크": "information-processing-framework",
    "기술수용모델": "technology-acceptance-model",
    "기술수용모델(tam)": "technology-acceptance-model",
    "기술-수용-모델": "technology-acceptance-model",
    "기술-불안": "techno-anxiety",
    "디지털-역량": "digital-capability",
    "디지털-활용능력": "digital-literacy",
    "디지털-탐색능력": "digital-search-capability",
    "디지털-생태계": "digital-ecosystem",
    "소셜-미디어": "social-media",
    "기술": "technology",
    "기술사업화능력": "technology-commercialization",
    "기술경쟁력": "technological-competitiveness",
    "기술혁신성": "technological-innovativeness",

    # 전략/경쟁
    "경쟁우위": "competitive-advantage",
    "경쟁-우위": "competitive-advantage",
    "지속가능한-경쟁-우위": "sustained-competitive-advantage",
    "전략경영": "strategic-management",
    "전략-경영": "strategic-management",
    "전략적-관리": "strategic-management",
    "전략적-태도": "strategic-attitude",
    "전략수립": "strategy-formulation",
    "전략": "strategy",
    "경영전략": "business-strategy",
    "차별화전략": "differentiation-strategy",
    "원가우위전략": "cost-leadership-strategy",
    "경쟁전략": "competitive-strategy",
    "자원기반관점": "resource-based-view",
    "자원기반이론": "resource-based-view",
    "자원기반관점(rbv)": "resource-based-view",
    "동적역량": "dynamic-capabilities",
    "동태적능력": "dynamic-capabilities",
    "동역학-역량": "dynamic-capabilities",
    "동역량이론": "dynamic-capabilities",
    "동적역량이론": "dynamic-capabilities",
    "동적-역량-이론": "dynamic-capabilities",
    "흡수-역량": "absorptive-capacity",
    "흡수역량": "absorptive-capacity",
    "비즈니스-모델": "business-model",
    "경영": "management",
    "경쟁": "competition",

    # 조직행동/심리
    "신뢰": "trust",
    "사회적-자본": "social-capital",
    "사회적자본": "social-capital",
    "사회적영향": "social-influence",
    "사회교환이론": "social-exchange-theory",
    "사회적교환이론": "social-exchange-theory",
    "직무만족": "job-satisfaction",
    "직무-만족도": "job-satisfaction",
    "자기효능감": "self-efficacy",
    "지식-자기효능감": "knowledge-self-efficacy",
    "심리적-안전-분위기": "psychological-safety",
    "심리적-안전감": "psychological-safety",
    "심리적고용안정": "psychological-job-security",
    "조직몰입": "organizational-commitment",
    "조직-몰입": "organizational-commitment",
    "정서적몰입": "affective-commitment",
    "자율성": "autonomy",
    "직무자율성": "job-autonomy",
    "임파워먼트": "empowerment",
    "변혁적-리더십": "transformational-leadership",
    "위험": "risk",
    "위험감수성": "risk-taking",
    "위험-감수": "risk-taking",
    "진취성": "proactiveness",
    "선제적-지향성": "proactive-orientation",
    "동기부여": "motivation",
    "학습동기": "learning-motivation",
    "학습의지": "learning-willingness",
    "창의성": "creativity",
    "창의적-분위기": "creative-climate",
    "창의적-행동": "creative-behavior",
    "개인-창의성": "individual-creativity",
    "목표-지향성": "goal-orientation",
    "학습지향성": "learning-orientation",
    "학습-지향성": "learning-orientation",
    "일몰입": "work-engagement",
    "직무충실도": "job-enrichment",
    "조직-동일시": "organizational-identification",
    "인지된-조직지원": "perceived-organizational-support",
    "과업갈등": "task-conflict",
    "관계갈등": "relationship-conflict",
    "업무-상호의존성": "task-interdependence",
    "호혜성": "reciprocity",
    "친사회적-동기": "prosocial-motivation",
    "이미지-보존-동기": "image-protection-motivation",
    "구성원-마음챙김": "follower-mindfulness",
    "인지적-유연성": "cognitive-flexibility",
    "상식-추론": "commonsense-reasoning",
    "인지심리학": "cognitive-psychology",
    "인지-심리학": "cognitive-psychology",
    "뇌과학": "neuroscience",
    "경험적-학습": "experiential-learning",
    "회복탄력성": "resilience",

    # 공급망/운영
    "공급망-회복탄력성": "supply-chain-resilience",
    "공급망-복원력": "supply-chain-resilience",
    "공급망-성과": "supply-chain-performance",
    "공급망-역동성": "supply-chain-dynamics",
    "비즈니스-연속성-계획(bcp)": "business-continuity-planning",

    # 경제/거시
    "경제": "economics",
    "거시경제학": "macroeconomics",
    "경제-성장": "economic-growth",
    "내생적-성장-이론": "endogenous-growth-theory",
    "실물경기변동이론(rbc)": "real-business-cycle",
    "기술-충격": "technology-shock",
    "불확실성": "uncertainty",
    "환경-적대성": "environmental-hostility",
    "환경-불확실성": "environmental-uncertainty",
    "환경동태성": "environmental-dynamism",
    "시장": "market",
    "시장-지향성": "market-orientation",
    "경제사회학": "economic-sociology",
    "신흥-시장": "emerging-market",
    "신흥-경제": "emerging-economy",

    # SECI / 모델
    "seci-모델": "seci-model",
    "seci모델": "seci-model",
    "seci-과정": "seci-model",
    "sor-모델": "sor-model",
    "sor-프레임워크": "sor-model",
    "sor-이론": "sor-model",
    "s-o-r-모델": "sor-model",
    "toe-모델": "toe-model",
    "ba-(장)": "ba",

    # 국가/지역
    "인도네시아": "indonesia",
    "요르단": "jordan",
    "요르단-은행-산업": "jordan",
    "말레이시아": "malaysia",
    "사우디아라비아": "saudi-arabia",
    "베트남": "vietnam",
    "중국": "china",
    "인도": "india",
    "한국": "korea",

    # 산업/분야
    "호텔": "hotel",
    "관광": "tourism",
    "군조직": "military-organization",
    "호텔-산업": "hotel-industry",
    "환대-산업": "hospitality",
    "헬스케어-혁신": "healthcare-innovation",
    "스마트-헬스케어": "smart-healthcare",
    "항만": "port",
    "생산현장": "production-site",
    "건설-안전-관리": "construction-safety",

    # ESG/CSR
    "esg위원회": "esg",
    "esg성과": "esg-performance",
    "esg필요성": "esg",
    "csr위원회": "csr",
    "csr-활동": "csr",
    "그린워싱": "greenwashing",
    "기업지배구조": "corporate-governance",
    "녹색-지식-관리": "green-knowledge-management",
    "지속가능발전목표(sdg)": "sdg",
    "기업의-지속-가능한-발전(csd)": "corporate-sustainable-development",
    "탄소-배출": "carbon-emission",

    # 기타
    "튜링-테스트": "turing-test",
    "지적-자본": "intellectual-capital",
    "지적자본": "intellectual-capital",
    "사회적-자본-이론": "social-capital-theory",
    "자원기반관점": "resource-based-view",
    "지식-공간": "knowledge-space",
    "개인화": "personalization",
    "추천-시스템": "recommender-system",
    "추천시스템": "recommender-system",
    "지식재사용": "knowledge-reuse",
    "지식네트워크-분석": "knowledge-network-analysis",
    "지식전이": "knowledge-transfer",
    "지식허브": "knowledge-hub",
    "지식공유정도": "knowledge-sharing",
    "네트워크-역량": "network-capability",
    "협력네트워크": "cooperation-network",
    "사회적-네트워크": "social-network",
    "외부네트워크": "external-network",
    "정부지원": "government-support",
    "정부지원정책": "government-support-policy",
    "보상분배의-공정성": "reward-fairness",
    "보상체계": "reward-system",
    "보상제도": "reward-system",
    "직렬이중매개효과": "serial-dual-mediation",
    "조직성과급만족": "performance-based-pay-satisfaction",
    "경쟁가치모형": "competing-values-framework",
    "연령-다양성": "age-diversity",
    "고령인력": "older-workforce",
    "성별-편향": "gender-bias",
    "성별-차이": "gender-difference",
    "여성ceo": "female-ceo",
    "부모-자영업-(pse)": "parental-self-employment",
    "다국국-기업(mnc)": "multinational-corporation",
    "글로벌-기업": "global-company",
    "본사-해외자회사-관계": "headquarter-subsidiary",
    "해외자회사": "foreign-subsidiary",
    "수출-성과": "export-performance",
    "수출마케팅-역량": "export-marketing-capability",
    "중소기업-마케팅": "sme-marketing",
    "마케팅역량": "marketing-capability",
    "마케팅-커뮤니케이션": "marketing-communication",
    "구매-의도": "purchase-intention",
    "소비자-행동": "consumer-behavior",
    "경험적-소비": "experiential-consumption",
    "쾌락적-가치": "hedonic-value",
    "의사결정": "decision-making",
    "의사결정-이론": "decision-theory",
    "의사결정증강": "decision-augmentation",
    "의사결정(decision-making)": "decision-making",
    "r&d역량": "r&d-capability",
    "연구개발투자": "r&d-investment",
    "특허활동": "patent-activity",
    "특허권": "patent",
    "외부r&d지출": "external-r&d",
    "개인-지식-관리": "personal-knowledge-management",
    "기업가적-학습": "entrepreneurial-learning",
    "지식-공유(ks)": "knowledge-sharing",
    "한국학술지인용색인(kci)": "kci",
    "연구관련성": "research-relevance",
    "이론구축": "theory-building",
    "인식론": "epistemology",
    "지혜": "wisdom",
    "딕위(dikw)-계층": "dikw",
    "dikw-계층": "dikw",
    "담론": "discourse",
    "능력주의의-역설": "meritocracy-paradox",
    "프라이버시": "privacy",
    "의인화": "anthropomorphism",
    "유기농-식품": "organic-food",
    "디지털-광고": "digital-advertising",
    "sms-광고": "sms-advertising",
    "광고-가치": "advertising-value",
    "플랫폼-경제": "platform-economy",
    "공유-경제": "sharing-economy",
    "링크드-빌딩-데이터": "linked-building-data",
    "가설재-관리": "temporary-construction-management",
    "건설-자동화": "construction-automation",
    "코로나19": "covid-19",
    "기업교육": "corporate-education",
    "교수법": "pedagogy",
    "다차원적-교육": "multidimensional-education",
    "실패를-통한-학습풍토": "learning-from-failure",
    "학습-전달-기후": "learning-transfer-climate",
    "협력적-수업-설계": "collaborative-lesson-planning",
    "교사-전문성-개발": "teacher-professional-development",
    "기업가정신-교육": "entrepreneurship-education",
    "신경창업학(neuroentrepreneurship)": "neuroentrepreneurship",
    "세무-회계": "tax-accounting",
    "세무-리스크": "tax-risk",
    "감사시장-집중도": "audit-market-concentration",
    "감사품질": "audit-quality",
    "감사보수": "audit-fee",
    "감사인-지정제": "auditor-designation",
    "회계법인": "accounting-firm",
    "생산역량": "production-capability",
    "조직설계": "organizational-design",
    "메타-분석": "meta-analysis",
    "교환-관계": "exchange-relationship",
    "장점": "advantages",
    "정통성-할인": "legitimacy-discount",
    "시장-범주화": "market-categorization",
    "증권분석가": "securities-analyst",
    "상위-집단-이론": "upper-echelon-theory",
    "인지된유용성": "perceived-usefulness",
    "기술혁신성": "technological-innovativeness",
    "가치혁신문화": "value-innovation-culture",
    "내생적-성장-이론": "endogenous-growth-theory",
    "산업-유형": "industry-type",
    "산업구조혁신": "industrial-structure-innovation",
    "정보공유": "information-sharing",
    "정보-비대칭": "information-asymmetry",
    "정보-검색": "information-retrieval",
    "정보시스템-성공모델": "information-system-success-model",
    "중국기업": "chinese-firms",
    "중국-농촌-경제": "chinese-rural-economy",
    "농민-창업": "rural-entrepreneurship",
    "사우디아라비아": "saudi-arabia",
    "인도네시아": "indonesia",
    "오만-대학생": "oman",
    "이집트-세제": "egypt",
    "폴란드-기업-연구": "poland",
    "남아프리카-공화국-중소기업": "south-africa",
    "지식기반비즈니스(kibs)": "kibs",
    "전문인력양성": "professional-development",
    "지역-경쟁력": "regional-competitiveness",
    "협력적-커뮤니케이션": "cooperative-communication",
    "기업가적-생태계": "entrepreneurial-ecosystem",
    "자원-동원": "resource-mobilization",
    "자원활용-역량": "resource-utilization-capability",
    "자원활용도": "resource-utilization",
    "보유자원": "resources",
    "규제-환경": "regulatory-environment",
    "수출경쟁력": "export-competitiveness",
    "수출시장-지향성": "export-market-orientation",
    "구조적-공백": "structural-holes",
    "사이중앙성": "betweenness-centrality",
    "변증법": "dialectics",
    "지식-표현": "knowledge-representation",
    "논리-프로그래밍": "logic-programming",
    "어드바이스-테이커": "advice-taker",
    "시맨틱-세그멘테이션": "semantic-segmentation",
    "시퀀스-투-시퀀스": "sequence-to-sequence",
    "컴퓨터-비전": "computer-vision",
    "기회-발견": "opportunity-discovery",
    "기회-인식-및-활용": "opportunity-recognition",
    "lmx-차별화(lmxd)": "lmx-differentiation",
    "네트워크-비순환성": "network-acyclicity",
    "권력-거리": "power-distance",
    "r&d-혁신": "r&d-innovation",
    "지식-외부효과": "knowledge-spillover",
    "상식-추론": "commonsense-reasoning",
    "오픈-사이언스": "open-science",
    "학술출판주기": "academic-publishing",
    "학술-출판": "academic-publishing",
    "chatgpt-품질": "chatgpt-quality",
    "활용만족": "use-satisfaction",
    "지속적-이용의도": "continuance-intention",
    "기대일치이론": "expectation-confirmation-theory",
    "미디어-콘텐츠": "media-content",
    "3i-전략": "3i-strategy",
    "숏폼-비디오": "short-form-video",
    "빈지-스크롤링": "binge-scrolling",
    "자기통제력-상실": "self-control-loss",
    "무한-스크롤": "infinite-scroll",
    "디지털-웰빙": "digital-wellbeing",
    "스타트업-개발": "startup-development",
    "gem-데이터": "gem-data",
    "글로벌-기업가정신-모니터(gem)": "gem",
    "기업가적-활동": "entrepreneurial-activity",
    "기업-윤리": "business-ethics",
    "ai-pen-프레임워크": "ai-pen-framework",
    "hail-프레임워크": "hail-framework",
    "heaal-프레임워크": "heaal-framework",
    "딕위-계층": "dikw",
    "인간-자율성": "human-autonomy",
    "인식적-대리인": "epistemic-agent",
    "ai-창업": "ai-entrepreneurship",
    "금융-규제": "financial-regulation",
    "신호-이론": "signaling-theory",
    "스타트업-성과": "startup-performance",
    "매개-효과": "mediating-effect",
    "창업-생태계": "entrepreneurial-ecosystem",
    "구조방정식-모델링(sem)": "structural-equation-modeling",
    "지속-가능한-혁신": "sustainable-innovation",
    "인지적-근접성": "cognitive-proximity",
    "비즈니스-방법-특허": "business-method-patent",
    "sor-이론": "sor-model",
    "헬스케어-스타트업": "healthcare-startup",
    "4차산업혁명": "industry-4.0",
    "고등교육-기관": "higher-education",
    "개방형혁신": "open-innovation",
    "특허권": "patent",
    "xg부스트": "xgboost",
    "예측-모델": "predictive-model",
    "생성적-적대-신경망(gan)": "gan",
    "데이터-불균형": "data-imbalance",
    "베이지안-네트워크": "bayesian-network",
    "행동-기반-안전": "behavior-based-safety",
    "게임-분석": "game-analysis",
    "죄수의-딜레마": "prisoners-dilemma",
    "내쉬-균형": "nash-equilibrium",
    "모방-게임": "imitation-game",
    "디지털-컴퓨터": "digital-computer",
    "보편-기계": "universal-machine",
    "기계-지능": "machine-intelligence",
    "기대효용-이론": "expected-utility-theory",
    "프로스펙트-이론": "prospect-theory",
    "가치-함수": "value-function",
    "의사결정-가중치": "decision-weights",
    "매장-분위기": "store-atmosphere",
    "환경-심리학": "environmental-psychology",
    "소매업": "retail",
    "건설-시간(time-to-build)": "time-to-build",
    "비시계열적-효용": "non-time-separable-utility",
    "기술-충격": "technology-shock",
    "전략수립": "strategy-formulation",
    "조직유형론": "organizational-typology",
    "상황이론": "contingency-theory",
    "기업-생애주기": "corporate-life-cycle",
    "조직-진화": "organizational-evolution",
    "경험적-소비": "experiential-consumption",
    "놀이-이론": "play-theory",
    "감정-반응(pad)": "emotional-response",
    "내재적-동기": "intrinsic-motivation",
    "비디오-게임-연구": "video-game-research",
    "기업가-정신-동기": "entrepreneurial-motivation",
    "상호-신뢰": "mutual-trust",
    "상위-집단-이론": "upper-echelon-theory",
    "기업이론": "theory-of-firm",
    "조직설계": "organizational-design",
    "메타-분석": "meta-analysis",
    "교환-관계": "exchange-relationship",
    "공급망-회복탄력성": "supply-chain-resilience",
    "조직민첩성": "organizational-agility",
    "팀-공유감": "team-shared-cognition",
    "팀-응집성": "team-cohesion",
    "중국-보건의료": "chinese-healthcare",
    "농촌-만성질환-관리": "rural-chronic-disease",
    "중국-도시": "chinese-urban",
    "구현-로드맵": "implementation-roadmap",
    "빅데이터-거버넌스": "big-data-governance",
    "비즈니스-인텔리전스": "business-intelligence",
    "비즈니스-인텔리전스(business-intelligence)": "business-intelligence",
    "비즈니스-인큐베이터": "business-incubator",
    "가치창출": "value-creation",
    "공유-경제": "sharing-economy",
    "디지털-라이브러리": "digital-library",
    "추천-시스템": "recommender-system",
    "사용자-인터랙션": "user-interaction",
    "척도-개발-및-타당화": "scale-development",
    "기업가적-지식-창출": "entrepreneurial-knowledge-creation",
    "상황-판단-테스트": "situational-judgment-test",
    "경험적-학습": "experiential-learning",
    "인지-심리학": "cognitive-psychology",
    "이사회하위위원회": "board-subcommittee",
    "유대강도": "tie-strength",
    "환경-불확실성": "environmental-uncertainty",
    "계획된-행동-이론-(tpb)": "theory-of-planned-behavior",
    "창업-의도": "entrepreneurial-intention",
    "구조방정식-(sem-pls)": "pls-sem",
    "정보기술": "information-technology",
    "비즈니스기회": "business-opportunity",
    "제조": "manufacturing",
    "ai-창업": "ai-entrepreneurship",
    "주요사항보고서분석": "material-disclosure-analysis",
    "학술기관": "academic-institution",
    "실패를-통한-학습풍토": "learning-from-failure",
    "알고리즘-통제": "algorithmic-control",
    "노동-과정-이론": "labor-process-theory",
    "알고액티비즘": "algoactivism",
    "경합-지대": "contested-space",
    "디지털-노동": "digital-labor",
    "jd-r-모델": "jd-r-model",
    "관계-결속": "relationship-ties",
    "경계-확장-행동": "boundary-spanning-behavior",
    "운영-관리(om)": "operations-management",
    "거시경제지표": "macroeconomic-indicators",
    "양면적혁신활동": "ambidextrous-innovation",
    "업무-인수인계": "job-handover",
    "벤처창업": "venture",
    "개방형혁신": "open-innovation",
    "글로벌터미널운영사(gto)": "global-terminal-operator",
    "오픈-사이언스": "open-science",
    "chatgpt-품질": "chatgpt-quality",
    "연구-윤리": "research-ethics",
    "지속적-이용의도": "continuance-intention",
    "유체역학": "fluid-dynamics",
    "특이점-형성": "singularity-formation",
    "물리-정보-신경망(pinn)": "physics-informed-neural-network",
    "자기-유사-해": "self-similar-solution",
    "편미분-방정식(pde)": "partial-differential-equation",
    "gauss-newton-최적화": "gauss-newton-optimization",
    "내부특유자원": "firm-specific-resources",
    "인적자원역량": "hr-capability",
    "경쟁우위전략": "competitive-advantage-strategy",
    "혁신활동결과": "innovation-activity-outcomes",
    "상생협력활동": "win-win-cooperation",
    "조직적-자본": "organizational-capital",
    "인사프랙티스": "hr-practices",
    "심리적고용안정": "psychological-job-security",
    "조직성과급만족": "performance-based-pay-satisfaction",
    "진성-리더십": "authentic-leadership",
    "상호피드백": "mutual-feedback",
    "디지털-역량": "digital-capability",
    "팀-공유감": "team-shared-cognition",
    "팀-응집성": "team-cohesion",
    "인지된-조직지원": "perceived-organizational-support",
    "지식서비스산업": "knowledge-intensive-services",
    "전문인력양성": "professional-development",
    "지식기반비즈니스(kibs)": "kibs",
    "정부지원정책": "government-support-policy",
    "산업구조혁신": "industrial-structure-innovation",
    "협력네트워크": "cooperation-network",
    "협력적-커뮤니케이션": "cooperative-communication",
    "지식-영역성": "knowledge-territoriality",
    "녹색-지식-관리": "green-knowledge-management",
    "녹색-혁신": "green-innovation",
    "조직-녹색-문화": "green-organizational-culture",
    "지속가능발전목표(sdg)": "sdg",
    "기업의-지속-가능한-발전(csd)": "corporate-sustainable-development",
    "지식-관리-시스템(kms)": "knowledge-management-system",
    "지식-근로자": "knowledge-worker",
    "프로세스-재설계": "process-redesign",
    "코로나19": "covid-19",
    "인공지능-전략": "ai-strategy",
    "인공-자본": "artificial-capital",
    "지식-기반-관점": "knowledge-based-view",
    "인간-ai-협업": "human-ai-collaboration",
    "협력적-수업-설계": "collaborative-lesson-planning",
    "교사-전문성-개발": "teacher-professional-development",
    "척도-개발-및-타당화": "scale-development",
    "기업가적-암묵지": "entrepreneurial-tacit-knowledge",
    "상황-판단-테스트": "situational-judgment-test",

    # 추가 미매핑 태그
    "시스템": "system",
    "소기업-경영": "small-business-management",
    "상황-이론": "contingency-theory",
    "일본식-경영": "japanese-management",
    "미들-업-다운-관리": "middle-up-down-management",
    "허즈버그-2요인-이론": "herzberg-two-factor-theory",
    "전략적도구": "strategic-tool",
    "조직경쟁력": "organizational-competitiveness",
    "논문-분석": "paper-analysis",
    "데이터-오류": "data-error",
    "학술-논문": "academic-paper",
    "불균형-프레임워크": "disequilibrium-framework",
    "선구성": "proactiveness",
    "경쟁적-공격성": "competitive-aggressiveness",
    "미시적-기반": "microfoundations",
    "성과-기반-보상": "performance-based-compensation",
    "외부-환경-인식": "environmental-perception",
    "지식친화적인-팀문화": "knowledge-friendly-team-culture",
    "팀원간-신뢰": "team-trust",
    "웹-분석": "web-analytics",
    "노사커뮤니케이션": "labor-management-communication",
    "근로자참여": "worker-participation",
    "컨설턴트": "consultant",
    "역량": "capability",
    "혁신성공요인": "innovation-success-factors",
    "it-서비스": "it-services",
    "메신저시스템": "messenger-system",
    "법집행기관": "law-enforcement",
    "합리적행동이론": "theory-of-reasoned-action",
    "계획된행동이론": "theory-of-planned-behavior",
    "프로세스-접근법": "process-approach",
    "네트워킹-패턴": "networking-pattern",
    "활동성-차원": "activity-dimension",
    "코스닥기업": "kosdaq-firm",
    "생산공정방식": "production-process",
    "디지털-기술": "digital-technology",
    "변화-관리": "change-management",
    "경제순환": "economic-cycle",
    "하이테크-스타트업": "high-tech-startup",
    "데이터-전략": "data-strategy",
    "사회과학": "social-science",
    "심리학": "psychology",
    "인지과학": "cognitive-science",
    "투명성": "transparency",
    "해석가능성": "interpretability",
    "수용의도": "adoption-intention",
    "디지털-포용-금융": "digital-financial-inclusion",
    "활성화-요인": "enabling-factors",
    "저해-요인": "inhibiting-factors",
    "개발-방법론": "development-methodology",
    "기업가-활동": "entrepreneurial-activity",
    "예측": "prediction",
    "지도-학습": "supervised-learning",
    "외부조력자프레임워크": "external-facilitator-framework",
    "의미-부여": "sensemaking",
    "위기-관리": "crisis-management",
    "강한-지속가능성": "strong-sustainability",
    "트리플-바텀-라인": "triple-bottom-line",
    "건강-형평성": "health-equity",
    "의료-거버넌스": "healthcare-governance",
    "자기인지-창의성": "self-perceived-creativity",
    "게임-회사": "game-company",
    "서비스-산업": "service-industry",
    "기업역량": "firm-capability",
    "양면성-이론": "ambidexterity-theory",
    "조직-내-경쟁": "intra-organizational-competition",
    "상대평가": "relative-evaluation",
    "공공기관-비교연구": "public-institution-comparison",
    "경쟁-불안": "competitive-anxiety",
    "근무-의욕": "work-motivation",
    "정치적-양극화": "political-polarization",
    "필터-버블": "filter-bubble",
    "정치경제학": "political-economy",
    "약국-산업": "pharmacy-industry",
    "측량학적-분석": "bibliometric-analysis",
    "조직-지식": "organizational-knowledge",
    "지식-유출": "knowledge-leakage",
    "지속가능-경영": "sustainable-management",
    "기술-진보": "technological-progress",
}


def normalize_tag(tag: str) -> str:
    """태그를 정규화하여 영문으로 반환. 매핑 없으면 원본 반환."""
    tag = tag.strip()
    # 매핑 직접 일치
    if tag in TAG_MAP:
        return TAG_MAP[tag]
    # 소문자로 시도
    if tag.lower() in TAG_MAP:
        return TAG_MAP[tag.lower()]
    return tag


def process_file(fpath: str, dry_run: bool = False) -> bool:
    """단일 파일의 태그를 영문으로 정규화. 변경 시 True 반환."""
    content = open(fpath, encoding="utf-8").read()

    # --- YAML tags 업데이트 ---
    yaml_match = re.search(r'^(tags:\s*\[)(.+?)(\])', content, re.MULTILINE)
    if not yaml_match:
        return False

    raw_tags = [t.strip() for t in yaml_match.group(2).split(",")]
    # base 태그 (literature, paper) 유지, 나머지 정규화
    base = [t for t in raw_tags if t in ("literature", "paper")]
    others = [t for t in raw_tags if t not in ("literature", "paper")]

    normalized = []
    for t in others:
        n = normalize_tag(t)
        normalized.append(n)

    # 중복 제거 (순서 유지)
    seen = set()
    deduped = []
    for t in base + normalized:
        if t not in seen:
            seen.add(t)
            deduped.append(t)

    new_tags_str = ", ".join(deduped)
    old_tags_str = yaml_match.group(2)

    if new_tags_str == old_tags_str:
        return False

    new_yaml = yaml_match.group(1) + new_tags_str + yaml_match.group(3)
    new_content = content[:yaml_match.start()] + new_yaml + content[yaml_match.end():]

    # --- 본문 해시태그 업데이트 ---
    hashtag_match = re.search(r'(\*\*태그\*\*: )(.*?)(\n)', new_content)
    if hashtag_match:
        tag_list = [t for t in deduped if t not in ("literature", "paper")]
        new_hashtags = " ".join(f"#{t}" for t in tag_list)
        new_content = (
            new_content[:hashtag_match.start()]
            + hashtag_match.group(1) + new_hashtags + hashtag_match.group(3)
            + new_content[hashtag_match.end():]
        )

    if not dry_run:
        open(fpath, "w", encoding="utf-8").write(new_content)
    return True


def main():
    import argparse
    parser = argparse.ArgumentParser(description="한글 태그 → 영문 정규화")
    parser.add_argument("--dry-run", action="store_true", help="변경 없이 대상만 출력")
    args = parser.parse_args()

    md_dir = str(MARKDOWN_DIR)
    files = sorted([f for f in os.listdir(md_dir) if f.endswith(".md")])

    changed = 0
    for fname in files:
        fpath = os.path.join(md_dir, fname)
        if process_file(fpath, dry_run=args.dry_run):
            changed += 1
            if args.dry_run:
                print(f"  변경 예정: {fname}")

    print(f"\n{'[dry-run] ' if args.dry_run else ''}{'변경 예정' if args.dry_run else '변경 완료'}: {changed}개 / 전체 {len(files)}개")


if __name__ == "__main__":
    main()
